{"name": "test_func", "status": "failed", "statusDetails": {"message": "AssertionError: assert [1, 2, 3] == [1, 2, 4]\n  At index 2 diff: 3 != 4\n  Full diff:\n  - [1, 2, 3]\n  ?        ^\n  + [1, 2, 4]\n  ?        ^", "trace": "def test_func():\n        def func():\n            return [1,2,3]\n    \n>       assert func() == [1,2,4]\nE       assert [1, 2, 3] == [1, 2, 4]\nE         At index 2 diff: 3 != 4\nE         Full diff:\nE         - [1, 2, 3]\nE         ?        ^\nE         + [1, 2, 4]\nE         ?        ^\n\ntests/test_assertions.py:33: AssertionError"}, "start": 1591177964078, "stop": 1591177964078, "uuid": "80ca3c01-f997-4790-a671-9f6478d82f97", "historyId": "c7deb80c02a641c44581a601d8aa78ec", "testCaseId": "ab2a61770e0e2adc57d2cc47c52ef550", "fullName": "tests.test_assertions#test_func", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_assertions"}, {"name": "host", "value": "LIUMENGJIAdeMacBook-Pro.local"}, {"name": "thread", "value": "78362-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_assertions"}]}