{"name": "test_set", "status": "failed", "statusDetails": {"message": "AssertionError: assert {0, 1, 11, 23} == {0, 2, 11}\n  Extra items in the left set:\n  1\n  23\n  Extra items in the right set:\n  2\n  Use -v to get the full diff", "trace": "self = <tests.test_assertions.TestCollections object at 0x103554f90>\n\n    def test_set(self):\n>       assert {0,1,11,23} == {0,11,2}\nE       assert {0, 1, 11, 23} == {0, 2, 11}\nE         Extra items in the left set:\nE         1\nE         23\nE         Extra items in the right set:\nE         2\nE         Use -v to get the full diff\n\ntests/test_assertions.py:56: AssertionError"}, "start": 1591176793781, "stop": 1591176793781, "uuid": "fb546629-db73-4430-9884-52613ca75a0b", "historyId": "ab5141e061250e4f2638fbbce67d3ff0", "testCaseId": "61b71ab9b43aa9e506f5b561e4436abb", "fullName": "tests.test_assertions.TestCollections#test_set", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_assertions"}, {"name": "subSuite", "value": "TestCollections"}, {"name": "host", "value": "LIUMENGJIAdeMacBook-Pro.local"}, {"name": "thread", "value": "78122-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_assertions"}]}